# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('email', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=1500)),
                ('subject', models.CharField(max_length=4)),
                ('course_number', models.CharField(max_length=4)),
            ],
        ),
    ]
